name: Graphs CI with Teams Notification

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  release:
    name: Generate graphs and notify Teams
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT || github.token }}

      - name: Generate graphs
        uses: upptime/uptime-monitor@v1.40.1
        with:
          command: "graphs"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Notify Microsoft Teams
        run: |
          PAYLOAD=$(jq -n \
            --arg text "📊 Upptime: Graphs have been updated for [${{ github.repository }}](https://github.com/${{ github.repository }})" \
            '{text: $text}')
          curl -H 'Content-Type: application/json' \
            -d "$PAYLOAD" \
            "${{ secrets.TEAMS_WEBHOOK_URL }}"
