name: Notify Teams on Status Change

on:
  push:
    branches:
      - main  # Change to 'master' if your default branch is master

jobs:
  notify:
    name: Notify Teams
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch recent history to access latest commit
          token: ${{ secrets.GH_PAT || github.token }}

      - name: Pull latest commit (ensure correct logs)
        run: git pull origin ${{ github.event.repository.default_branch }}

      - name: Get last commit message
        id: commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=format:"%s")
          echo "message=$COMMIT_MSG" >> $GITHUB_OUTPUT

      - name: Notify Microsoft Teams
        if: contains(steps.commit.outputs.message, '游린') || contains(steps.commit.outputs.message, '游릴')
        run: |
          COMMIT_MSG="${{ steps.commit.outputs.message }}"
          STATUS=$(echo "$COMMIT_MSG" | grep -o '游린\|游릴')
          SITE=$(echo "$COMMIT_MSG" | sed -E 's/.*游린 (.*) is.*/\1/' | sed -E 's/.*游릴 (.*) is.*/\1/')
          STATE=$(echo "$COMMIT_MSG" | sed -E 's/.* is (.*)/\1/')

          if [[ "$STATUS" == "游린" ]]; then
            EMOJI="游댮"
            TEXT="$EMOJI DOWN: **$SITE**\n游린 $SITE is $STATE"
          else
            EMOJI="游릭"
            TEXT="$EMOJI UP: **$SITE**\n游릴 $SITE is $STATE"
          fi

          curl -H 'Content-Type: application/json' \
               -d "{\"text\": \"$TEXT\"}" \
               "${{ secrets.TEAMS_WEBHOOK_URL }}"
