name: Upptime Teams Notifications

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes
  workflow_dispatch:

jobs:
  notify:
    name: Check and Notify Teams
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT || github.token }}

      - name: Get latest commit message
        id: commit
        run: |
          echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Send Teams Notification
        if: |
          contains(steps.commit.outputs.message, '游린') ||
          contains(steps.commit.outputs.message, '游릴')
        run: |
          COMMIT_MSG="${{ steps.commit.outputs.message }}"

          # Extract website name and status
          if [[ "$COMMIT_MSG" == *"游린"* ]]; then
            STATUS="游댮 DOWN"
          else
            STATUS="游릭 UP"
          fi

          # Extract just the site name from commit message (e.g., "knocen")
          SITE=$(echo "$COMMIT_MSG" | grep -oP '(?<=游린 |游릴 ).*?(?= is)' || echo "unknown")

          # Compose payload
          PAYLOAD=$(jq -n \
            --arg text "$STATUS: **$SITE**\n\n$COMMIT_MSG" \
            '{text: $text}')

          curl -H 'Content-Type: application/json' \
            -d "$PAYLOAD" \
            "${{ secrets.TEAMS_WEBHOOK_URL }}"
